In [1]:
import pandas as pd
import numpy as np
import os
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv(r'./WineQT.csv')

In [3]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [4]:
df.drop(columns=['Id'],axis=1,inplace=True)

In [5]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 107.3 KB

In [7]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [9]:
x=df.drop(columns=['pH'])
y=df['pH']

In [10]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [11]:
model=LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
model.predict(x_test)

array([3.5884675 , 3.45996066, 3.39466769, 3.34338926, 3.47845186,
       3.53065464, 3.45357424, 3.39516902, 3.08388152, 3.25804515,
       3.24026634, 3.25173099, 3.20139961, 3.19510642, 3.55804866,
       3.23735331, 3.1311212 , 3.31352636, 3.26776847, 3.33597249,
       3.00072749, 3.49999075, 3.52533638, 3.41259913, 3.34271325,
       3.13314798, 3.23168809, 2.96192915, 3.46572018, 3.29964508,
       3.4748691 , 3.20754209, 3.41175205, 3.24862261, 3.33837601,
       3.55972513, 3.31528156, 3.49430818, 3.26598611, 3.46846095,
       3.25546291, 3.06977181, 3.39231977, 3.43058488, 2.76250417,
       3.28234849, 3.37905494, 3.25841714, 3.28124984, 3.29827201,
       3.26889638, 3.41144903, 3.3796018 , 3.25182718, 3.18950631,
       3.40697555, 3.29211067, 3.40966869, 3.06343868, 3.31020019,
       3.33047084, 3.33373688, 3.25027881, 3.35606307, 3.22113372,
       3.40030905, 3.21515028, 3.55863151, 3.13207522, 3.44859956,
       3.37300587, 3.38243894, 3.26897812, 3.22192736, 3.34177195,
       3.41590435, 3.45158399, 3.32636961, 3.25593336, 3.40009015,
       3.39031254, 3.25825318, 3.29292415, 3.47588528, 3.33288164,
       3.41179173, 3.306239  , 3.24142946, 3.2932518 , 3.22653102,
       3.41983087, 3.57222898, 3.33597249, 3.17170315, 3.40742063,
       3.45815479, 3.49362363, 3.45229677, 3.28260427, 3.36267136,
       3.33921639, 3.29648651, 3.25739176, 3.42952218, 3.40644636,
       2.95029899, 3.50331962, 3.42079518, 3.28462953, 3.2666211 ,
       3.27799002, 3.55224531, 3.26206478, 3.0167434 , 3.2808043 ,
       3.2600518 , 3.25542974, 3.35636109, 3.42528694, 3.35217718,
       3.03286751, 3.18390632, 3.44427482, 3.41882672, 3.11940538,
       3.5536769 , 3.39492066, 3.34180146, 3.34334859, 3.12202443,
       3.3144538 , 3.08512437, 3.22958322, 3.48137553, 3.37160656,
       3.44697145, 3.43280624, 3.33612586, 3.21460422, 3.37279759,
       3.40595327, 3.26966206, 3.40062882, 3.068379  , 3.34578038,
       3.32933675, 3.26889638, 3.47667039, 3.33634736, 3.3587268 ,
       3.37782173, 3.25841714, 3.16330369, 3.36373416, 3.28923131,
       3.39933952, 2.99264755, 3.2371087 , 3.32636961, 3.33496057,
       2.99035378, 3.22327977, 3.22102445, 3.32183374, 3.51139801,
       3.37273601, 3.19303869, 3.28391669, 3.48919906, 3.17720927,
       3.41716124, 3.10465329, 3.01910276, 3.28140614, 3.28960567,
       3.32644628, 3.0813276 , 3.45884338, 3.4427933 , 3.42411365,
       3.40656924, 3.13426468, 3.22446287, 3.30345303, 3.41880065,
       3.38962586, 3.38795568, 3.20089685, 3.36062658, 3.38467815,
       3.39363834, 3.23049863, 3.28512972, 3.55972513, 3.30194716,
       3.23064989, 2.93488975, 3.35321747, 3.18220239, 3.36467025,
       3.26190503, 3.26512913, 3.15923321, 3.3798098 , 3.57009372,
       3.3765915 , 2.89581791, 3.25955495, 3.32772724, 3.26124102,
       3.27004168, 3.44085498, 3.15683608, 3.16087311, 3.35148817,
       3.5884675 , 3.36496933, 3.27471835, 3.28132503, 3.11078086,
       3.49999075, 3.07262932, 3.23120471, 3.49596011, 3.28328815,
       3.02553412, 3.30124952, 3.53812781, 3.23736889])

In [14]:
with open('model.pkl','wb') as file:
    pickle.dump(model,file)

In [15]:
with open('model.pkl','rb') as file:
    pkl_file=pickle.load(file)

In [16]:
pkl_file

LinearRegression()